version: 1.0.{build}

environment:
  matrix:
  - name: win64
    platform: amd64_x64
    qt: msvc2017

build_script:
  - call "D:\program tools\Microsoft Visual Studio\2019\community\VC\Auxiliary\Build\vcvarsall.bat" x64_amd64
  - set QTDIR-C:\Qt\Qt5.9.0\5.9\msvc2017_64
  - set PATH-%PATH%;%QTDIR%\bin;
  - qmake
  - nmake & exit 0